Repository kubernetes-sigs/sig-windows-dev-tools, pull requests merged in 2021-07, with the labels that each got.

#41 Antrea retry
  forked/1-antrea.ps1
  sync/shared/kubejoin.ps1
Labels: cncf-cla: yes, size/S

#42 Remove nat network
  Vagrantfile
  forked/1-antrea.ps1
  forked/Install-Containerd.ps1
  forked/PrepareNode.ps1
  sync/shared/kubejoin.ps1
  sync/windows/containerd1.ps1
  sync/windows/k.ps1
Labels: cncf-cla: yes, size/L

#44 Update README.md
  README.md
Labels: cncf-cla: yes, size/M

#48 Prepare node optimizations
  forked/PrepareNode.ps1
  sync/shared/kubejoin.ps1
Labels: cncf-cla: yes, size/M

#49 remove extra download logic that is obviated by the retrier
  forked/PrepareNode.ps1
Labels: cncf-cla: yes, size/S

#47 added wirnm to Prerequisites in readme
  README.md
Labels: cncf-cla: yes, size/S

#53 Calico support 3
  README.md
  Vagrantfile
  forked/config.ps1
  sync/linux/calico-0.sh
  sync/linux/controlplane.sh
  sync/shared/kubejoin.ps1
  sync/shared/variables.yaml
Labels: cncf-cla: yes, size/S

#59 Jayunit100/friedrich robox
  Vagrantfile
  forked/Install-Containerd.ps1
  sync/linux/calico-0.sh
  sync/linux/smoke-test.yaml
  sync/shared/kubejoin.ps1
Labels: cncf-cla: yes, size/S

#62 Calico fix : use the right service-cidr
  forked/config.ps1
  sync/shared/kubejoin.ps1
  sync/shared/variables.yaml
Labels: cncf-cla: yes

#61 OWNERS file fixes + updates
  OWNERS
  OWNERS_ALIASES
Labels: cncf-cla: yes, lgtm, size/S

#63 Split the calico node startup into an async step and run node startup separately
  Vagrantfile
  forked/1-calico.ps1
  forked/2-calico.ps1
  forked/calico.psm1
  forked/config.ps1
  forked/install-calico-windows.ps1
  forked/install-calico.ps1
  makefile
Labels: approved, cncf-cla: yes, size/M
