Repository kubernetes-sigs/sig-windows-dev-tools, pull requests merged in 2021-09, with the labels that each got.

#94 added cgroup driver flag
  sync/linux/controlplane.sh
Labels: cncf-cla: yes, size/XS

#95 Adding knabben to OWNERS file
  OWNERS
  OWNERS_ALIASES
Labels: cncf-cla: yes, do-not-merge/invalid-owners-file, size/XS

#96 Tweak readme to avoid confusion over vagrant up
  README.md
Labels: cncf-cla: yes, approved, lgtm, size/XS

#97 Update antrea-agent-windows-x86_64.exe link of v1.3.0
  forked/0-antrea.ps1
Labels: cncf-cla: yes, approved, lgtm, size/XS

#101 Adding image-builder diagram
  experiments/image-builder/README.md
  experiments/image-builder/image-builder.sh
  experiments/image-builder/images/diagram.jpg
Labels: cncf-cla: yes, size/S, approved, lgtm

#106 adding image builder files
  experiments/image-builder/image-builder.sh
  experiments/image-builder/images/.gitignore
  experiments/image-builder/images/overlays/autounattend.xml
Labels: cncf-cla: yes, size/L, approved, lgtm

#107 Increasing overlay
  experiments/image-builder/.gitignore
  experiments/image-builder/image-builder.sh
  experiments/image-builder/overlays/ansible/roles/cni/tasks/main.yml
  experiments/image-builder/overlays/autounattend.xml
  experiments/image-builder/overlays/packer-windows.json
  experiments/image-builder/overlays/vm-guest-tools.ps1
Labels: cncf-cla: yes, size/L, approved, lgtm

#109 adding choco and vim (via choco)
  experiments/image-builder/image-builder.sh
  experiments/image-builder/overlays/ansible/roles/cni/tasks/main.yml
  experiments/image-builder/overlays/ansible/roles/utilities/tasks/main.yml
Labels: cncf-cla: yes, size/S, approved, lgtm

#108 Downloading Calico requirements on box
  experiments/image-builder/image-builder.sh
  experiments/image-builder/overlays/ansible/roles/utilities/tasks/main.yml
Labels: cncf-cla: yes, size/M, approved, lgtm
