Repository kubernetes-sigs/sig-windows-dev-tools, pull requests merged in 2021-08, with the labels that each got.

#69 Calico, third try, clean implementation w/ no extra commits
  README.md
  Vagrantfile
  forked/calico.psm1
  forked/calico.yaml
  forked/install-calico-windows.ps1
  forked/install-calico.ps1
  makefile
  sync/linux/calico-0.sh
  sync/shared/kubejoin.ps1
  sync/windows/hyperv.ps1
Labels: approved, cncf-cla: yes, size/L

#66 Enabling SSH service
  README.md
  Vagrantfile
  sync/windows/ssh.ps1
Labels: cncf-cla: yes, size/M, approved, lgtm

#84 Vxlan adapter configurable
  .gitignore
  Vagrantfile
  forked/1-calico.ps1
  forked/3-calico.ps1
  forked/PrepareNode.ps1
  forked/config.ps1
  forked/node-service.ps1
  sync/linux/controlplane.sh
  sync/shared/kubejoin.ps1
  sync/shared/variables.yaml
Labels: cncf-cla: yes, size/L, approved, lgtm

#89 Update smoke-test.yaml
  sync/linux/smoke-test.yaml
Labels: cncf-cla: yes, size/M, approved, lgtm

#90 Update Antrea Windows agent link
  forked/0-antrea.ps1
Labels: cncf-cla: yes, size/XS
