Repository kubernetes-sigs/sig-windows-dev-tools, pull requests merged in 2022-01, with the labels that each got.

#140 bump calicoooo 3.20-2
  forked/calico.yaml
  sync/linux/calico-0.sh
Labels: cncf-cla: yes, size/S, approved, lgtm

#145 controlplane: copy crictl.exe to containerd dir
  sync/linux/controlplane.sh
Labels: cncf-cla: yes, approved, lgtm, size/XS

#141 build: add .lock for cni and joined
  .gitignore
  Vagrantfile
  makefile
Labels: cncf-cla: yes, size/S, approved, lgtm

#164 Removing Kubernetes version from Antrea install
  Vagrantfile
  build.sh
  sync/linux/controlplane.sh
  sync/linux/smoke-test.yaml
  sync/windows/1-antrea.ps1
Labels: cncf-cla: yes, size/L, approved, lgtm

#165 Updating windows before joining the node
  README.md
  Vagrantfile
  makefile
  sync/linux/smoke-test.yaml
  sync/shared/variables.yaml
  sync/windows/updates.ps1
Labels: cncf-cla: yes, do-not-merge/hold, size/M, approved, lgtm

#169 Removing kubectl from antrea install
  sync/windows/0-antrea.ps1
Labels: cncf-cla: yes, size/S, approved, lgtm

#171 Moving windows updates to a new box
  Vagrantfile
  experiments/image-builder/image-builder.sh
  experiments/image-builder/overlays/packer-windows.json
  makefile
  sync/windows/0-antrea.ps1
  sync/windows/1-antrea.ps1
  sync/windows/updates.ps1
Labels: cncf-cla: yes, size/M, approved, lgtm

#178 calico: Bind the cluster role to the calico-node
  sync/linux/calico-0.sh
Labels: cncf-cla: yes, approved, lgtm, size/XS

#180 calico: add missing rbac
  forked/calico.yaml
  sync/linux/calico-0.sh
Labels: cncf-cla: yes, approved, lgtm, size/XS

#173 make: do not show commands
  makefile
Labels: cncf-cla: yes, size/M, approved, lgtm
