Repository kubernetes-sigs/sig-windows-dev-tools, pull requests merged in 2023-02, with the labels that each got.

#224 Calico as a HostProcess container
  Vagrantfile
  debug-power-shell-cmds
  doubt
  kpng/ds.yaml
  kpng/sa.yaml
  steps
  sync/linux/calico-0.sh
  sync/linux/controlplane.sh
  sync/linux/untitled
  sync/windows/0-containerd.ps1
  sync/windows/0-kubelet.ps1
  variables.yaml
Labels: cncf-cla: yes, size/L, approved, lgtm

#226 change of path in calico Install-Containerd script
  sync/windows/0-containerd.ps1
Labels: cncf-cla: yes, approved, lgtm, size/XS

#228 Add calico version support into download calico
  Vagrantfile
  experiments/image-builder/overlays/packer-windows.json
  sync/linux/calico-0.sh
  sync/windows/0-containerd.ps1
  variables.yaml
Labels: cncf-cla: yes, size/M, approved, lgtm, tide/merge-method-squash
