Repository kubernetes-sigs/sig-windows-dev-tools, pull requests merged in 2023-05, with the labels that each got.

#268 Address issues raised in #264 post-merge review
  Vagrantfile
  magefiles/config.go
  magefiles/run.go
Labels: cncf-cla: yes, size/M, approved, lgtm

#271 Latest update to master-windows-native
  .gitignore
  README.md
  docs/usage.md
  docs/wsl.md
  magefiles/binaries.go
  magefiles/build.go
  magefiles/clean.go
  magefiles/cluster.go
  magefiles/fetch.go
  magefiles/main.go
  magefiles/node.go
  magefiles/status.go
  settings.yaml
  sync/linux/controlplane.sh
Labels: cncf-cla: yes, size/XL, approved, lgtm

#274 Updated vagrantfile with winrm and smb specific configurations.
  Vagrantfile
Labels: cncf-cla: yes, size/S, approved, lgtm
