Repository kubernetes-sigs/sig-windows-dev-tools, pull requests merged in 2023-03, with the labels that each got.

#230 fix argument quoting and version reporting
  Vagrantfile
  sync/windows/0-containerd.ps1
Labels: cncf-cla: yes, approved, lgtm, size/XS

#231 ubuntu update -y and logging stuff
  sync/linux/controlplane.sh
Labels: cncf-cla: yes, size/S, do-not-merge/hold, approved, lgtm

#232 Replacing k8s.grc.io with registry.k8s.io
  sync/linux/wine2e.yaml
Labels: cncf-cla: yes, approved, lgtm, size/XS

#234 added dissable firewall
  sync/windows/ssh.ps1
Labels: cncf-cla: yes, approved, lgtm, size/XS

#236 Added qemu provider support to bring up the cluster
  Makefile
  Vagrantfile
Labels: cncf-cla: yes, size/M, approved, lgtm

#237 Qemu on mac amd64 testing
  Vagrantfile
  sync/linux/controlplane.sh
  variables.yaml
Labels: cncf-cla: yes, size/S, approved
