Repository kubernetes-sigs/sig-windows-dev-tools, pull requests merged in 2023-04, with the labels that each got.

#250 Ignore /sync/shared/variables.yaml copied from /variables.yaml
  .gitignore
Labels: cncf-cla: yes, approved, lgtm, size/XS

#256 Fix crictl.exe file not found in %PATH% regression
  sync/linux/controlplane.sh
Labels: cncf-cla: yes, approved, lgtm, size/XS

#257 Ensure copied Kubernetes binaries are executable
  sync/linux/controlplane.sh
Labels: cncf-cla: yes, approved, lgtm, size/XS

#258 Remove unwanted files
  debug-power-shell-cmds
  doubt
  kpng/ds.yaml
  kpng/sa.yaml
  steps
  sync/linux/untitled
Labels: cncf-cla: yes, size/L, kind/cleanup, approved, lgtm

#264 Switch to custom Vagrant boxes and Magefiles instead of Makefile
  .gitignore
  README.md
  Vagrantfile
  go.work
  magefiles/build.go
  magefiles/clean.go
  magefiles/fetch.go
  magefiles/go.mod
  magefiles/go.sum
  magefiles/main.go
  magefiles/run.go
  magefiles/status.go
  magefiles/test.go
Labels: cncf-cla: yes, size/XL, approved, lgtm

#265 Remove Makefile and run README.md update
  Makefile
  README.md
  Vagrantfile
  build.sh
  docs/other.md
  docs/testing.md
  docs/ubuntu.md
  docs/windows.md
  fetch.sh
Labels: cncf-cla: yes, size/XL, approved, lgtm

#262 Vagrantfile: Clean up accidentally interleaved vm.provider and vm.synced_folder
  Vagrantfile
Labels: cncf-cla: yes, size/S, approved, lgtm

#251 Rename trigera to correct tigera (copy of #241 fixed issue_239 typo)
  sync/linux/calico-0.sh
Labels: cncf-cla: yes, approved, lgtm, size/XS

#266 Rework Vagrant and cluster configuration settings with Mage targets
  .gitignore
  README.md
  Vagrantfile
  magefiles/build.go
  magefiles/clean.go
  magefiles/config.go
  magefiles/fetch.go
  magefiles/go.mod
  magefiles/go.sum
  magefiles/main.go
  magefiles/run.go
  magefiles/status.go
  magefiles/test.go
  settings.yaml
  variables.yaml
Labels: cncf-cla: yes, size/XL, approved, lgtm

#267 Add mage targets to create/destroy/start/stop individual nodes
  README.md
  magefiles/node.go
Labels: cncf-cla: yes, size/L, approved, lgtm
