Repository kubernetes-sigs/sig-windows-dev-tools, pull requests merged in 2024-01, with the labels that each got.

#277 docs: Add "Quo Vadis SWDT" discussing project issues and ideas
  docs/quo-vadis-swdt.md
Labels: cncf-cla: yes, size/L, approved, lgtm

#275 Clarify support
  README.md
Labels: cncf-cla: yes, size/M, approved, lgtm

#278 Experimental CLI and SDK for remote node control
  experiments/swdt/.gitignore
  experiments/swdt/LICENSE
  experiments/swdt/Makefile
  experiments/swdt/README.md
  experiments/swdt/apis/config/v1alpha1/config_types.go
  experiments/swdt/apis/config/v1alpha1/defaults.go
  experiments/swdt/apis/config/v1alpha1/groupversion_info.go
  experiments/swdt/apis/config/v1alpha1/zz_generated.deepcopy.go
  experiments/swdt/apis/config/v1alpha1/zz_generated.defaults.go
  experiments/swdt/cmd/root.go
  experiments/swdt/cmd/setup.go
  experiments/swdt/go.mod
  experiments/swdt/go.sum
  experiments/swdt/hack/boilerplate.go.txt
  experiments/swdt/main.go
  experiments/swdt/pkg/config/config.go
  experiments/swdt/pkg/config/config_test.go
  experiments/swdt/pkg/connections/interface.go
  experiments/swdt/pkg/connections/ssh.go
  experiments/swdt/pkg/connections/ssh_test.go
  experiments/swdt/pkg/pwsh/setup/setup.go
  experiments/swdt/samples/config.yaml
Labels: cncf-cla: yes, size/XXL, approved

#280 fix(cli): Execute PowerShell command via SSH as oneliner
  experiments/swdt/pkg/connections/ssh.go
  experiments/swdt/pkg/pwsh/setup/setup.go
Labels: cncf-cla: yes, size/S, approved, lgtm

#281 feat(cli): Add convenience go run runners for SWDT CLI
  .gitignore
  swdt.ps1
  swdt.sh
Labels: cncf-cla: yes, size/M, approved, lgtm

#283 refactor(cli): Rename API type Config to Node
  experiments/swdt/README.md
  experiments/swdt/apis/config/v1alpha1/config_types.go
  experiments/swdt/apis/config/v1alpha1/defaults.go
  experiments/swdt/apis/config/v1alpha1/zz_generated.deepcopy.go
  experiments/swdt/cmd/setup.go
  experiments/swdt/pkg/config/node.go
  experiments/swdt/pkg/config/node_test.go
  experiments/swdt/samples/config.yaml
Labels: cncf-cla: yes, size/M, approved, lgtm

#282 test(cli): Start guide on testing Windows VM on Windows host
  experiments/swdt/README.md
  experiments/swdt/samples/mloskot/.gitignore
  experiments/swdt/samples/mloskot/README.windows.md
  experiments/swdt/samples/mloskot/ssh.id_rsa
  experiments/swdt/samples/mloskot/ssh.id_rsa.pub
  experiments/swdt/samples/mloskot/winworker.yaml
Labels: cncf-cla: yes, size/L, approved, lgtm

#284 refactor(cli): Rename API type DeploySpec to ProvisionerSpec
  experiments/swdt/README.md
  experiments/swdt/apis/config/v1alpha1/config_types.go
  experiments/swdt/apis/config/v1alpha1/zz_generated.deepcopy.go
  experiments/swdt/pkg/config/node_test.go
  experiments/swdt/samples/config.yaml
  experiments/swdt/samples/mloskot/winworker.yaml
Labels: cncf-cla: yes, size/M, approved, lgtm

#285 Knabben/fix choco deps
  experiments/swdt/cmd/setup.go
  experiments/swdt/pkg/pwsh/setup/setup.go
  experiments/swdt/pkg/pwsh/setup/setup_test.go
Labels: cncf-cla: yes, size/M, approved

#287 Fixing branches filter for github actions
  .github/workflows/golangci-lint.yml
  .github/workflows/tests.yml
  experiments/swdt/cmd/kubernetes.go
  experiments/swdt/cmd/setup.go
  experiments/swdt/pkg/connections/tests/server.go
  experiments/swdt/pkg/pwsh/executor/runner_test.go
  experiments/swdt/pkg/pwsh/kubernetes/provisioners.go
  experiments/swdt/pkg/pwsh/setup/setup.go
Labels: cncf-cla: yes, size/M, approved

#279 Adding Mateusz Loskot as subproject owner
  OWNERS
Labels: cncf-cla: yes, approved, lgtm, size/XS

#288 Add pre-commit configuration with basic linters
  .pre-commit-config.yaml
  experiments/swdt/cmd/root.go
  swdt.sh
Labels: cncf-cla: yes, size/M, approved, lgtm

#289 fix(cli): session.Run is sensitive to quoting on Windows host
  experiments/swdt/pkg/connections/ssh.go
  experiments/swdt/pkg/pwsh/setup/setup.go
Labels: cncf-cla: yes, approved, lgtm, size/XS

#290 fix(cli): choco executable is not in PATH
  experiments/swdt/pkg/pwsh/setup/setup.go
  experiments/swdt/pkg/pwsh/setup/setup_test.go
Labels: cncf-cla: yes, approved, size/XS

#292 feat(cli): First stab at structured contextual logging via go-logr API
  experiments/swdt/cmd/kubernetes.go
  experiments/swdt/cmd/root.go
  experiments/swdt/cmd/setup.go
  experiments/swdt/go.mod
  experiments/swdt/go.sum
  experiments/swdt/main.go
  experiments/swdt/pkg/config/node.go
  experiments/swdt/pkg/connections/ssh.go
Labels: cncf-cla: yes, size/L, approved, lgtm
